import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;

public  class Main {
    public static void main(String[] args) {
        String url = "jdbc:oracle:thin:@localhost:1521:XE";
        String usuario = "RIBERA";
        String contraseña = "ribera";
        Scanner sc = new Scanner(System.in);

        try (Connection conn = DriverManager.getConnection(url, usuario, contraseña)) {
            Statement statement = conn.createStatement();

            String sqlDROPArtista = "DROP TABLE ARTISTA CASCADE CONSTRAINTS; ";
            try {
                statement.executeUpdate(sqlDROPArtista);
            }catch (Exception e){
                //ignora
            }

            String sqlDROPConcierto = "DROP TABLE CONCIERTO CASCADE CONSTRAINTS; ";
            try {
                statement.executeUpdate(sqlDROPConcierto);
            }catch (Exception e){
                //ignora
            }

            String sqlDROPEntrada = "DROP TABLE ENTRADA CASCADE CONSTRAINTS; ";
            try {
                statement.executeUpdate(sqlDROPEntrada);
            }catch (Exception e){
                //ignora
            }

            String sqlArtista =
                    "CREATE TABLE ARTISTA ( " +
                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "nombre VARCHAR2(100) NOT NULL, " +
                        "generoMusical VARCHAR2(50), " +
                        "paisOrigen VARCHAR2(50) " +
                    "); ";
            statement.executeUpdate(sqlArtista);

            String sqlConcierto =
                    "CREATE TABLE CONCIERTO ( " +
                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "artista_id NUMBER, " +
                        "fecha DATE, " +
                        "lugar VARCHAR2(100), " +
                        "precioEntrada NUMBER(10, 2), " +
                        "FOREIGN KEY (artista_id) REFERENCES Artista(id) " +
                    "); ";
            statement.executeUpdate(sqlConcierto);

            String sqlEntrada =
                    "CREATE TABLE ENTRADA ( " +
                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "concierto_id NUMBER, " +
                        "comprador VARCHAR2(100), " +
                        "cantidad NUMBER, " +
                        "fechaCompra DATE, " +
                        "FOREIGN KEY (concierto_id) REFERENCES Concierto(id) " +
                    "); ";
            statement.executeUpdate(sqlEntrada);

            System.out.println("tablas creadas");

        }catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
}